### ISSUE TITLE
Login screen - Spotify Auth

### ISSUE THREAD

**Issue by JoseRenan** [JoseRenan/idontknowmyname#1]
### Task description

Create a simple login screen only with a button to allow [Spotify oAuth](https://developer.spotify.com/web-api/authorization-guide/) that gets the permission to `user-read-recently-played` token and redirects to the user's profile initial page.

### Things to do:

- [x]  Create the screen with the button to Spotify auth;
- [x]  Make the request to retrieve the token and store temporarily;

**Comment by FannyVieira** [comment]
Good! Can i make a pr?

**Comment by JRobsonJr** [comment]
Go there!
